name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubunu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    - name: install node
      uses: actions/setup-input@v3
    - run: npm install -g bats
    - run: bats -v
    - run: echo  "힘내 오늘도!"
    - run: echo "나는 ${github.actor}야!"
    - run: "${github.event}"
